ball homework
Funya1337/ball-jquery- pull request #1
Opened 2018-01-14 18:41 UTC by Funya1337

2018-01-14 19:04 UTC, klishevich requested changes
please fix

2018-01-14 19:04 UTC, klishevich commented on css/style.css
> +.block-left{width:50%;height:800px;float:left;}
please make right indentation

2018-01-14 19:04 UTC, klishevich commented on index.html
> +    <center>
do not use center element

2018-01-15 14:43 UTC, Funya1337 commented on index.html
> +    <center>
why?

2018-01-15 18:04 UTC, merged